### ISSUE TITLE
HRM PROD DEFECT

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/SSO-HRM#53]
@lalitharajendiran 

Assigned work from home & entered report. then unassigned WFH.

But using ADMIN REPORT SEARCH UPDATE.  NO DATA AVALIABLE CAME.CANNT USE THE ADMIN SEARCH . FIX AND RE DELIVER IMMEDIATELY

![image](https://cloud.githubusercontent.com/assets/9882142/14410005/e3b02df8-ff40-11e5-8039-1155f9c71f7e.png)

**Comment by lalitharajendiran** [comment]
i checked in form side, we restricted if 1970 came means that err msg will come.so i think some report date wrongly saved in db (1970-01-01).so need latest backup from prod.

**Comment by DHANDAPANISATTANATHAN** [comment]
@lalitharajendiran 

I checked date saved 10/4 & 11/04 only.also using user report search i can search my records.

Issue is after select WFH and saved only,Fix this today!

**Comment by lalitharajendiran** [comment]
I CHECKED BACKUP PROD DATA UPTO YESTERDAY RECORDS,ONE RECORD SAVED IN 1970,SO NOW  RESTRICTED IN FORM SIDE(btn validation and before saving/updating checked conditions) .
AND  LOADED LATEST DB IN INT SCHEMA.

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: Task

@RAJALAKSHMIRAJKUMAR 

# write patch to update 1970 date in HRM PROD

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
I checked prod data for vishwa for march 26th timestamp repeatedly cumming to time. One record saved as 1970-01-01 another record saved as 2016-03-26 with same records. So need to delete 1970 record.

I discuss with sn sir he ask to delete that 1970 record.

Patch completed

https://drive.google.com/drive/folders/0Bwv4Rd7ZecjPVHFIcmpIekMtOUk

file name : SP_TS_DELETE_15893_VER_0.1_16042016

Status : **Done**

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: to_be_tested

Test in uat

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: verified

Tested in uat and now Admin report search loading.

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: Integrated

Int in HRM prod

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: to_be_tested

In HRM Prod

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: Veified

Tested in HRM PROD WORKING FINE
